
export const FACTURE_ADD = 'FACTURE_ADD';
export const FACTURE_FINAL_ADD = 'FACTURE_FINAL_ADD';
export const PRODUIT_ADD = 'PRODUIT_ADD';
export const FETCH_LISTE_FACTURE_REQUEST = 'FETCH_LISTE_FACTURE_REQUEST';
export const FETCH_LISTE_FACTURE_SUCCESS = 'FETCH_LISTE_FACTURE_SUCCESS';
export const FETCH_LISTE_FACTURE_SET_PAGE = 'FETCH_LISTE_FACTURE_SET_PAGE';